version: '3'
services:
  ansible:
    build: .
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TARGET_HOST=${TARGET_HOST}
      - TARGET_USER=${TARGET_USER}
      - TARGET_PASSWORD=${TARGET_PASSWORD}
    volumes:
      - .:/ansible