services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ansible
      - ${SSH_KEY_PATH:-~/.ssh}:/root/.ssh:ro  # Mount SSH keys if needed
    env_file:
      - .env
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_FORCE_COLOR=true
    # Default command can be overridden via command line
    command: site.yml 